### ISSUE TITLE
Control-Panel should move to CMFPlone

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.imaging#12]
Like all other control-panel views from plone.app.controlpanel the configlet of this package should be ported to z3c.form and move to CMFPlone.

**Comment by gforcada** [comment]
+1, are there more controlpanels that should be moved as well? It would be good to collect them on https://github.com/plone/Products.CMFPlone/issues/184

**Comment by tomgross** [comment]
All controlpanel items are listed in http://localhost:8080/Plone/portal_controlpanel/manage_editActionsForm
I don't know which of them are ported already.

**Comment by vangheem** [comment]
This is done with these pull requests:

- https://github.com/plone/Products.CMFPlone/pull/495
- https://github.com/plone/plone.app.imaging/pull/13
- https://github.com/plone/plone.app.upgrade/pull/31

**Comment by gforcada** [comment]
I added a .cfg on buildout.coredev 5.0 branch to tests all three branches together:

http://jenkins.plone.org/view/PLIPs/job/plip-imaging-controlpanel/1/

**Comment by vangheem** [comment]
thank you.

**Comment by gforcada** [comment]
I guess everything is done, closing then, great job @vangheem and thanks for pointing to it @tomgross!!
