### ISSUE TITLE
Deprecated on Plone 5.2?

### ISSUE THREAD

**Issue by cekk** [plone/plone.app.imaging#37]
@pbauer is this product deprecated on Plone 5.2? Or maybe is it merged inside the core?
Because the master has a dependency to Archetypes, and Archetypes are deprecated on Plone 5.2 (at least on python3).

**Comment by agitator** [comment]
yes, the scaling view aka @@images is now in https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/scaling.py
